
name: action-io-generator CI
on:
  push:
  pull_request:

defaults:
  run:
    working-directory: action-io-generator

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint

  compile_test:
    name: Compile and test
    runs-on: ubuntu-20.04
    env:
      TEST_FILE: test/generated/inputs-outputs.ts

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run lint
      - run: npm run compile
      - run: npm run bundle

      ##### End compile steps

      - name: Prepare to test
        run: rm -v ${{ env.TEST_FILE }}

      - name: Test as library
        run: npm run test

      - name: Sniff test enum file
        shell: bash
        run: |
          set -x
          [[ -f ${{ env.TEST_FILE }} ]]
          grep "export enum Inputs" ${{ env.TEST_FILE }}
          grep "export enum Outputs" ${{ env.TEST_FILE }}
          LINES=$(wc -l ${{ env.TEST_FILE }} | awk '{ print $1 }')
          (( LINES > 30 ))

      - name: Clean up
        run: rm -v ${{ env.TEST_FILE }}

      - name: Test as CLI
        run: npm run test-cli

      - name: Sniff test new enum file
        shell: bash
        run: |
          set -x
          [[ -f ${{ env.TEST_FILE }} ]]
          grep "export enum Inputs" ${{ env.TEST_FILE }}
          grep "export enum Outputs" ${{ env.TEST_FILE }}
          LINES=$(wc -l ${{ env.TEST_FILE }} | awk '{ print $1 }')
          (( LINES > 30 ))

      - name: Clean up again
        run: rm -v ${{ env.TEST_FILE }}

      ##### End test steps
